name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: echo "Building project..."

      - name: Deploy
        run: |
        echo "Using secret: ${{ secrets.DEEPSEEK_API_KEY }}"
        echo "Using secret: ${{ secrets.GOOGLE_GENAI_API_KEY }}"
        echo "Using secret: ${{ secrets.OPENAI_API_KEY }}"
        
